# Generated by Django 4.0 on 2022-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=True, max_length=5000),
            preserve_default=False,
        ),
    ]
