# Generated by Django 4.0 on 2022-09-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videou', '0003_alter_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
